### PR TITLE
Correct type spec

### PR DESCRIPTION
**Pull request by rubikill**
Correct type spec for content parameter

### CODE REVIEW

**Comment by gutschilla** [comment]
Hi @rubikill , thanks for pointing this out! The spec must by `html | {:url, url} | {:html, html}` though. I'll fix this.

**Comment by gutschilla** [comment]
Please see https://github.com/onpointvn/elixir-pdf-generator/compare/feature/update-spec...gutschilla:patch-1

**Comment by rubikill** [comment]
yeah, that's correct, I miss the `{:html, html}` case :)

**Comment by gutschilla** [comment]
Oops, this completely went under my radar. Thanks a lot!

**Pull request merged**
