### PR TITLE
Generate pdf from url

### PR DESCRIPTION
**Pull request by egze**
Now you can also generate a PDF from a URL.
```Elixir
pdf_path = PdfGenerator.generate "http://www.google.com"
```

Included a basic test as well.

### CODE REVIEW

**Comment by nivanson** [comment]
Reading the code I was first glance not sure if https would work. Both http and https works just fine however.

**Comment by egze** [comment]
@nivanson It's because I pattern match the url like this `"http" <> url` and then later create the full_url back with the url part. `full_url  = "http#{url}"`.

So if the parameter was let's say `"https://www.google.com"`, it would bind url to `"s://www.google.com"`. And then later full_url will become `"https://www.google.com"` back.

**Comment by gutschilla** [comment]
Heloo @egze,

first of all, thanks a lot for your contribution. It's cool seeing this library being use. 

I will not accept/merge this PR.

- I do not want the dependency to Poison and its dependencies
- Many users of this library already use some some of HTTP retrieval or even render their HTML on their own with one of the many libraries to do that out there. So adding this extra dependency is a cost for no benefit.

In production  code, one _should_ split the generation/retrieval of your HTML source from PDF generation anyways as it's a different concern. HTTP can always fail and handling errors their should belong to some HTTP-handling code.

```elixir
with {:ok, invoice} <- MyApp.Invoicing.Queries.get_by_id("foo-bar-id"),
     {:ok, html}    <- MyApp.Invoicing.Transformations.get_htmlfor(invoce),
     {:ok, pdf}     <- PdfGenerator.generate(html) do
{:ok, pdf}
end
```

or using some API wrapper

```elixir
with {:ok, html} <- ExternalSystem.InvoiceAPI.get_invoice_html(id: "foo-bar-id"),
     {:ok, pdf}     <- PdfGenerator.generate(html) do
{:ok, pdf}
end
```

**Comment by egze** [comment]
@gutschilla Thanks for your input. 

But I have to disagree.

1. About `poison` - it is a dependency for `fake_server`, which is only used for testing. It is not needed at all for end users. If `poison` is really a problem - maybe we can think of some alternative way how to test it?

2. The benefit. 1 big problem when you render HTML to PDF - is how you resolve other assets (images and css). Just rendering a pdf from string forces you to have all the resources either inline or available on disc. If you are in control of the `html` output - sure, no problem. But if you are forced to convert a 3rd party url - this is where it gets difficult. Because web pages can be quite complex - I find it hard to believe, that someone wrote a library that prepares the whole package that they can feed to `elixir-pdf-generator`. Also `wkhtmltopdf` supports passing a url, so for a wrapper, it would be nice to support the original functionality.

Please reconsider. I think this something that `elixir-pdf-generator` do need.

**Comment by gutschilla** [comment]
@egze Thanks for your input and reflection on the topic.

You are right, in my use cases external CSS and imagery uses absolute URLs as the underlying framework makes it easy to do so. So I get your point and will reconsider. Thank you.

Please allow for another day for me to get through the sources.

**Comment by nivanson** [comment]
I think it makes sense to keep api different for url and html.

Something like ```PdfGenerator.generate(html)``` and ```PdfGenerator.generate_from_url(url)```

**Comment by gutschilla** [comment]
@nivanson @egze There's a new version 0.5.0 that that

- support URLs via `generate({url: url})`
- supports chrome-headless via `generate(content, generator: :chrome)`

See: https://github.com/gutschilla/elixir-pdf-generator/releases/tag/v0.5.0

**Comment by egze** [comment]
Thanks a lot! This is great news!

**Comment by gutschilla** [comment]
Sure, thanks a lot or the input. It's very valuable.

**Pull request closed without merging**
