### PR TITLE
Fix passing of --no-sandbox to chrome-option

### PR DESCRIPTION
**Pull request by gdancel**

### CODE REVIEW

**Comment by gutschilla** [comment]
@gdancel - I stumbled upon the same thing. It's an issue with Elixir's parameter passing which is fixed in Elixir 1.8 - at least for me.

Which Elixir version are you using. For Elixir 1.7 the equal sign is required. Unfortunately, for 1.8 it will break the command.

 Maybe I should introduce a version switch for a while after the version-dependency has been verified.

 What do you think? Please let me know of your environment.

**Comment by gdancel** [comment]
@gutschilla I'm using 1.6.6. I didn't know that it will break in 1.8. The workaround I ended up using is adding `shell_params: ["--chrome-option=--no-sandbox"]` in the options for `generate`. Since there's a way to disable sandbox without using app env I think it's up to you if you'd like to support old versions being apple to use app env to disable sandbox.

**Comment by gutschilla** [comment]
@gdancel Thanks for coming back to me on this issue. Since there's a workaround in place I'd say I will document this. I would rather not try to bump the minimum Elixir version for this. I basic docker scenarios, the no-sandbox option is pretty handy as you need to run as root from within the container - so at least for me it's important.

**Comment by gutschilla** [comment]
I am adding a "known issue" section right now. I will bump the minimum Elixir version to 1.7 for 0.6.0

**Pull request merged**
