### PR TITLE
Add generate_on_directory function

### PR DESCRIPTION
**Pull request by lucas-aragno**
Hey @gutschilla I've added a function to create the pdf file into a custom directory, I'm using my fork on my app but let me know what do you think about the PR

### CODE REVIEW

**Comment by gutschilla** [comment]
Hi @lucas-aragno ,

thanks a lot for the idea and the pull request! :-) Your ideas are very welcome!

I think sepcifying the output path instead of putting it to `/tmp/wherever` would be a useful feature. Questions:

- Are you OK with it then still using random filenames? 
- What about the option to specify the full output path including the file name? 
- Out of interest: What are you using your fork for?

Minor issues: 

- If you take a look at the _files changed_ section in your PR there are a lot of non-changes that only affect spacing or would add spaces to the end of lines. Please keep your changes a bit cleaner so only the really affected lines pop up there. That helps **a lot** reviewing them. If you need help with that I am happy to assist.
- Writing to a temp file should always succeed (OK, there's a full disc scenario). But as you point out in your comment, the directoty to write to could not be writable. Currently I have no idea what kind of error happens when the specified dierctory isn't writable to the current user. Maybe we should employ `File.stat` for this. Did you try to write to a non-writable directory?

Thanks a lot for your PR! I's be absolutely happy to add your feature but I'd like us both to think about if there could be more to it. 

Thanks for listening and best regards, Martin

**Comment by lucas-aragno** [comment]
@gutschilla  thanks for the answer!

Regarding your comments:

* Yeah I think I'll add the name so the parameter should be `./here/myfile.pdf` instead of `./here` what do you think about that interface?

* I'm writing a little mix project to create a resume from an html editor 😄 

about the issues

* Yeah I guess my editor killed most of the trailing spaces I'll work w/ nano or vim to make sure to keep everything ok

* I'll add a validation using `File.stat` too good catch!

one more thing Im just thinking about, should I change the version number of the mix?


I'll waiting for you response !

**Comment by gutschilla** [comment]
Hi @lucas-aragno ,

thanks a lot for fixing things. Since I am quite busy these days I'll be merging you PR a bit later this day (my timezone is Europe/Berlin). 

Regarding your question: Good point on the mix version but I'll be relaeasing this right after merging your PR and I'll be writing a proper CHANGELOG entry mentoning your contribution for this.

Thanks a lot for your contribution!

Best regards, Martin

**Comment by lucas-aragno** [comment]
Cool @gutschilla !

just squashed some commits, I think everything is in place! 


Regarding the editor. Now I used nano, but I have being using Atom before it might be b/c of some style plugins that I have in there that might kill trailing spaces and such


Let me know if you need something else!

**Comment by gutschilla** [comment]
Hi @lucas-aragno,

just wanted to let you know that I became kind of unavailable these days. I am not forgetting this issue but I sadly think I won't find the time to merge/release until the end of this week :-( Sorry

**Comment by lucas-aragno** [comment]
Hello @gutschilla !

No problem, im still using my fork, just let me know when it's merged and up to date on Hex :)

**Comment by gutschilla** [comment]
Sorry for leaving this thing unattended for almost two months, now. Anyhow I finally tool a look into it:

Your `generate_on_directory ` works as advertised. The only issue I see is that it's not possible to hand over any options to it (like, changing the output format from A4 to something else). So what about if `generate_on_directory ` was only invoking `generate` with on option `html_directoy: <path>` set?

This way we could keep both the API with function generate_on_directory being still present *and* allow al other options still to be processed.

**Comment by gutschilla** [comment]
I will close this since I feel this feature is outside of the scope of this project.

**Comment by Jagadish28** [comment]
Hello @gutschilla  This is my controller code

def generatePDF(conn, _params) do
    PdfGenerator.generate("<h1>Boom</h1>" , [open_password: nil, filename: 'jaga'])
 end

I followed every instruction from your documentation
when I executing this code only html file is writing in the tmp folder not pdf

when I inspecting the line it returned "{:error, ""}"  
Need help

**Comment by gutschilla** [comment]
@Jagadish28 Thanks for your question. 

1. Please open another issue. This one is 
  a. closed
  b. on another topic
2. 
  a. running `PdfGenerator.generate("" , [open_password: nil, filename: 'jaga'])` _works for me_, even though it doesn't make sense to hand an empty HTML string to it. Also, if you don't want to encrypt your PDF you may simply omit the `open_password` parameter.
  b. Since I cannot reproduce your error a link to your repository would be of help as I caanot possibly guess your configuration
  c. Are you **sure** that both `wkhtmltopdf` and `pdftk` are available you you machine's path?

**Pull request closed without merging**
